### PR TITLE
Add keymap shortcuts to tooltips.

### PR DESCRIPTION
**Pull request by OceanWolf**
Added keymap shortcuts to tooltips, auto-updates when keymap changes using events.

### CODE REVIEW

**Comment by OceanWolf** [comment]
Reaching the edge now of the features / refactors I would like to see in this MEP :) (as might tell from small features such as this one).

Actually just one more idea on internal workings, on a related subject to this one to aid with accessibility issues.  I would like to add tool specific shortcuts, something like:
1. User activates ToggleTool
2. Keymap deactivates (or something like that) so that keystrokes go straight to the tool.
3. User presses `Esc` and the keymap re-activates.

So for the pan tool, this might mean that the arrow buttons can now pan (instead of their default behaviour of navigation back/forwards).

Should I work on that here, or in a separate PR?

**Comment by fariza** [comment]
I like the idea of this PR, I will check it out after the "statusbar" 

Regarding new features, I find more useful something in the lines of a contextmenu widget or something like that, to be able to implement things like this https://github.com/matplotlib/matplotlib/issues/4028

**Comment by OceanWolf** [comment]
Hehe, nice.  As you know I have wanted to get this MEP ready for context-menus :).

However, I do think context-menus lie out of scope for this MEP.  I see the remit here as refactoring/creating the API for tools (and basically taking as much out of the backends as possible) so that we have a solid framework from which to go on and do things like context menus, but not actually work on new tool features right now.  Hence why I said "features / refactors for _this_ MEP".

If we get this tool specific shortcuts working, I think it becomes relatively easy for someone to implement matplotlib#4028 i.e. with the zoom tool activated, the user can press (x,y,z) to snap the zoom tool to only zoom along that axes (and even using +/- to zoom).

**Comment by fariza** [comment]
Actually the functionality is already there. The too can grab the key
events (there is a lock) in place. And it can implement the extra key
functions.

**Comment by OceanWolf** [comment]
Nice.  Can you give me an example?  I just tried pressing 'p' for pan, and pressed the up arrow key and then key-input stopped working (pressing the left, right arrow keys would move a highlight thingy along the toolbar).  Any idea why?

**Comment by fariza** [comment]
in `NavigationBase` there is `keypresslock`, so the tool only has to 
- acquire the `navigation.keypresslock`
- connect to the canvas `key_press_event` implementing its own callback 
- release the `navigation.keypresslock` when done with the tool

**Comment by OceanWolf** [comment]
Nice, so shall I implement it in this PR?  So that acquire on  `ToolToggleBase.enable`, and release on `ToolToggleBase.disable`.

I think on adding an `internal_keymap` to map keys to tool methods (e.g. left arrow to pan.left), so if key not in `internal_keymap` it passes it on to `NavigationBase`.  Basically acting as a key-mask over `NavigationBase`.

**Comment by fariza** [comment]
I don't think this PR is the right place.
Maybe a later example.

**Pull request closed without merging**
